version: '3'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
      ports:
      - "3000:3000"
  AresMarketMaster:
    build:
      context: ./apps/AresMarketMaster
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
